apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-server-ingress
  namespace: default
spec:
  rules:
  - host: myapp.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-myserver
            port:
                   number: 80
