
build_web:
	cd joke_web && docker build -t yoavklein3/joke_web  .
	docker push yoavklein3/joke_web:latest

build_api:
	cd joke_api && docker build -t yoavklein3/joke_api .
	docker push yoavklein3/joke_api:latest
