kind: PersistentVolume
apiVersion: v1
metadata:
  name: hostpath-pv
spec:
  storageClassName: localpath
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/output
