apiVersion: v1
kind: Pod
metadata:
  name: reader-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    command: ['cat', '/output/success.txt']
    volumeMounts:
    - name: pv-storage
      mountPath: /output
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: my-pvc
