apiVersion: v1
kind: Pod
metadata:
  name: writer-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    command: ['sh', '-c', 'echo "SUCCESS" > /output/success.txt']
    volumeMounts:
    - name: pv-storage
      mountPath: /output
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: my-pvc
