apiVersion: v1
kind: Pod
metadata:
  name: startup-pod
spec:
  containers:
  - name: startup
    image: busybox:latest
    command: [ "/bin/bash", "-c", "sleep 30 && echo hello > /hello.txt && sleep 3600" ]
    startupProbe:
      exec:
        command: ["cat", "/hello.txt"]
      failureThreshold: 4
      periodSeconds: 10

