apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: multi-container-pod
spec:
  containers:
  - name: failing
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
  - name: succeeding
    image: nginx
    command: ["sh", "-c", "while true; do echo Success!! >> /var/log/success.txt; sleep 60; done"]
