    apiVersion: v1
    kind: EncryptionConfig
    resources:
    - resources:
       - secrets
      providers:
        - aescbc:
            keys:
            - name: key1
                secret: D2MK6zepnsd2Q+GTfdS8twzhJUd30EEe2kZzSCGs7K4=
        - identity: {}
