
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: configmap
spec:
  containers:
  - name: demo
    image: ubuntu
    command: ["sleep", "3600"]
# one way to cosume config map data is with environment variables
    volumeMounts:
    - name: config
      mountPath: /var/story.txt
      subPath: story
      readOnly: true             
    - name: config
      mountPath: /var/nested/color
      subPath: color
  volumes:
  - name: config
    configMap:
      name: dog-config
     
