apiVersion: rbac.authorization.k8s.io/v1
# this role-binding allows yoav to read pods in the "my-app" namespace
# you need to already have a Role named "pod-reader" in the my-app namespace
kind: RoleBinding
metadata:
  name: read-pods
  namespace: my-app
subjects:
- kind: User
  name: yoav
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: my-app-sa
roleRef:
  kind: Role
  name: pod-reader # this must match the name of the Role you wish to bind to
  apiGroup: rbac.authorization.k8s.io
