apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  namespace: my-app
spec:
  serviceAccountName: my-app-sa
  containers:
  - name: curl
    image: byrnedo/alpine-curl
    command:
    - "sh"
    - "-c"
    - "sleep 10000"

