apiVersion: v1
kind: Pod
metadata:
  name: research
spec:
  terminationGracePeriodSeconds: 50
  containers:
    - name: net-tools
      image: yoavklein3/net-tools:0.2
      command: ["sleep", "3600"]
      lifecycle:
        preStop:
          exec:
            command: ["/bin/bash", "-c", "while [ true ]; do curl echo; sleep 10; done"]
