apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: nfs-pv
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
     requests:
       storage: 5Mi
       
