apiVersion: v1
kind: Pod
metadata:
  name: nfs-client
spec:
  containers:
  - name: nfs-client
    image: ubuntu:20.04
    command: ["sleep", "3600"]
    volumeMounts:
      - name: nfs
        mountPath: "/nfs-share"
  volumes:
  - name: nfs
    persistentVolumeClaim:
     claimName: nfs-pvc

