apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  labels:
    role: nfs-server
  namespace: nfs-pv
spec:
  nodeName: node2
  containers:
  - name: nfs-server
    image: erichough/nfs-server
    ports:
    - name: nfs
      containerPort: 2049
    - name: rpcbind
      containerPort: 111
    - name: statd
      containerPort: 32765
    - name: mountd
      containerPort: 32767 
    securityContext:
       privileged: true
    env:
    - name: NFS_EXPORT_0
      value: '/nfs-export *(rw,no_subtree_check)'
    volumeMounts:
    - name: export
      mountPath: '/nfs-export'
  volumes:
  - name: export
    hostPath:
      path: '/mnt/nfs-export'
