apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: nfs-pv
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 32765
  - name: statd
    port: 32767
  - name: rpcbind
    port: 111
  selector:
   role: nfs-server 
